(function(){
  const DATA_PATH='data/portfolio.json';
  const state={owner:'saikat-71',repo:'saikat-71.github.io',token:'',branch:'main',sha:null,data:null,pendingFiles:[]};
  const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function toast(msg,error=false){const t=$('toast');t.textContent=msg;t.className='toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='toast',3200)}
  function api(path,opts={}){opts.headers=Object.assign({'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'},opts.headers||{});if(state.token)opts.headers.Authorization='Bearer '+state.token;return fetch('https://api.github.com'+path,opts)}
  function b64utf8(s){return btoa(unescape(encodeURIComponent(s)))}
  function fileB64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(file)})}
  function slug(s){return String(s||'item').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,55)||'item'}
  async function getFile(path){const apiPath=path.split('/').map(encodeURIComponent).join('/');const r=await api(`/repos/${state.owner}/${state.repo}/contents/${apiPath}?ref=${encodeURIComponent(state.branch)}`);if(r.status===404)return null;if(!r.ok)throw new Error(await r.text());return r.json()}
  async function uploadFile(path,file){const content=await fileB64(file);const existing=await getFile(path);const body={message:`admin: update ${path}`,content,branch:state.branch};if(existing?.sha)body.sha=existing.sha;const r=await api(`/repos/${state.owner}/${state.repo}/contents/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).message||'File upload failed');return path}
  async function loadData(){const r=await api(`/repos/${state.owner}/${state.repo}/contents/${DATA_PATH}?ref=${encodeURIComponent(state.branch)}`);if(!r.ok)throw new Error((await r.json()).message||'Could not read portfolio data');const j=await r.json();state.sha=j.sha;state.data=JSON.parse(decodeURIComponent(escape(atob(j.content.replace(/\n/g,'')))));renderAll();$('lastUpdated').textContent='Last published: '+(state.data.site?.lastUpdated||'—')}
  async function connect(){state.owner=$('ghOwner').value.trim();state.repo=$('ghRepo').value.trim();state.token=$('ghToken').value.trim();if(!state.owner||!state.repo||!state.token)return toast('Enter GitHub username, repository and token.',true);try{const rr=await api(`/repos/${encodeURIComponent(state.owner)}/${encodeURIComponent(state.repo)}`);if(!rr.ok){let msg='GitHub connection failed';try{const er=await rr.json();msg=er.message||msg}catch(_){}if(rr.status===401)msg='Invalid or expired GitHub token.';if(rr.status===403)msg='GitHub token is missing repository Contents permission.';if(rr.status===404)msg='Repository not found. Check GitHub username and repository name.';throw new Error(msg)}const repo=await rr.json();state.branch=repo.default_branch||'main';await loadData();$('setupPanel').classList.add('hidden');$('dashboardPanel').classList.remove('hidden');$('guidePanel').classList.remove('hidden');$('status').classList.add('connected');$('status').innerHTML='<i class="fa-solid fa-circle"></i><span>Connected</span>';toast('Connected successfully.');}catch(e){toast(e.message||'Connection failed.',true)}}
  function renderAll(){renderAbout();renderProjects();renderSkills();renderCertificates();renderExperience();renderCourses();renderEducation();renderResearch();renderVisibility();renderStats();refreshAdminListTools();}
  function renderStats(){const root=$('adminStats');if(!root||!state.data)return;const items=[['Projects',(state.data.projects||[]).length],['Skills',(state.data.skills||[]).length],['Certificates',(state.data.certificates||[]).length],['Experience',(state.data.experience||[]).length],['Courses',(state.data.courses||[]).length],['Education',(state.data.education||[]).length],['Research',(state.data.research||[]).length]];root.innerHTML=items.map(x=>`<div class="admin-stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');}
  function addAdminListTools(kind){
    const tab=$('tab-'+kind);if(!tab||tab.querySelector('.admin-dashboard-tools'))return;
    const list=tab.querySelector('.item-list');if(!list)return;
    const tools=document.createElement('div');tools.className='admin-dashboard-tools';tools.innerHTML='<div class="admin-list-search"><i class="fa-solid fa-magnifying-glass"></i><input type="search" placeholder="Search '+kind+'..." aria-label="Search '+kind+'"></div><div class="admin-quick-actions"><button class="mini-btn" type="button" data-new="'+kind+'"><i class="fa-solid fa-plus"></i> Add</button></div>';
    tab.insertBefore(tools,list);
    const input=tools.querySelector('input');input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();list.querySelectorAll('.item-card').forEach(card=>{card.hidden=!!q&&!card.textContent.toLowerCase().includes(q)})});
  }
  function refreshAdminListTools(){['projects','skills','certificates','experience','courses','education','research'].forEach(addAdminListTools)}
  function markDirty(){const el=$('adminDirty');if(el)el.classList.add('show')}

  function listCard(title,meta,idx,kind){return `<div class="item-card"><div class="item-card-main"><h3>${esc(title)}</h3><p>${esc(meta)}</p></div><div class="item-actions"><button class="mini-btn" data-edit="${kind}" data-index="${idx}"><i class="fa-solid fa-pen"></i> Edit</button><button class="mini-btn danger" data-delete="${kind}" data-index="${idx}"><i class="fa-solid fa-trash"></i> Delete</button></div></div>`}
  function renderAbout(){const root=$('tab-about');if(!root)return;const a=state.data.about||{};const facts=(a.facts||[]).map(x=>`${x.label||''} | ${x.value||''} | ${x.icon||''}`).join('\n');root.innerHTML=`<div class="editor about-editor"><h3>About & Profile Content</h3><div class="editor-form"><div class="form-grid two"><label>Home profile name<input data-about="heroName" value="${esc(a.heroName||'')}"></label><label>Education subtitle<input data-about="heroSubtitle" value="${esc(a.heroSubtitle||'')}"></label></div><label>About section heading<input data-about="heading" value="${esc(a.heading||'')}"></label><label>About paragraphs — one paragraph per line<textarea data-about="paragraphs" rows="6">${esc((a.paragraphs||[]).join('\n'))}</textarea></label><div class="editor-note"><strong>Homepage metrics are automatic.</strong><span>Projects, Research and Experience counts are calculated directly from the corresponding Admin collections, so adding or deleting items updates the homepage automatically.</span></div><label>About facts — one per line, format: label | value | icon<textarea data-about="facts" rows="8">${esc(facts)}</textarea></label><div class="editor-actions"><button class="btn btn-primary" data-save-about>Save About Content</button></div><p class="editor-help">This controls the homepage profile card, About text and facts. Homepage Projects, Research and Experience counts are automatic from the Admin collections. Research Interests are intentionally not managed from Admin.</p></div></div>`;}
  function renderProjects(){const root=$('tab-projects');root.innerHTML=`<div class="item-list">${state.data.projects.map((p,i)=>listCard(p.title,(p.tech||[]).join(' • ')+' • '+(p.featured===false?'Not featured on home':'Featured on home'),i,'projects')).join('')||'<div class="empty">No projects yet.</div>'}</div><button class="btn btn-primary" data-new="projects"><i class="fa-solid fa-plus"></i> Add Project</button><div id="editor-projects" class="editor-slot"></div>`;}
  function renderSkills(){const root=$('tab-skills');root.innerHTML=`<div class="item-list">${state.data.skills.map((s,i)=>listCard(s.title,(s.skills||[]).join(' • '),i,'skills')).join('')||'<div class="empty">No skills yet.</div>'}</div><button class="btn btn-primary" data-new="skills"><i class="fa-solid fa-plus"></i> Add Skill Group</button><div id="editor-skills" class="editor-slot"></div>`;}
  function renderCertificates(){const root=$('tab-certificates');root.innerHTML=`<div class="item-list">${state.data.certificates.map((c,i)=>listCard(c.title,c.provider+' • '+(c.featured===false?'Not featured on home':'Featured on home'),i,'certificates')).join('')||'<div class="empty">No certificates yet.</div>'}</div><button class="btn btn-primary" data-new="certificates"><i class="fa-solid fa-plus"></i> Add Certificate</button><div id="editor-certificates" class="editor-slot"></div>`;}
  function renderExperience(){const root=$('tab-experience');root.innerHTML=`<div class="item-list">${state.data.experience.map((e,i)=>listCard(e.title,e.company+' • '+(e.featured===false?'Not featured on home':'Featured on home')+' • '+(e.currentlyWorking?((e.joiningDate||e.date||'')+' – Present'):(e.joiningDate&&e.endDate?(e.joiningDate+' – '+e.endDate):e.date)),i,'experience')).join('')||'<div class="empty">No experience yet.</div>'}</div><button class="btn btn-primary" data-new="experience"><i class="fa-solid fa-plus"></i> Add Experience</button><div id="editor-experience" class="editor-slot"></div>`;}
  function renderCourses(){const root=$('tab-courses');if(!root)return;root.innerHTML=`<div class="item-list">${(state.data.courses||[]).map((c,i)=>listCard(c.title,(c.provider||'Learning provider not added')+' • '+(c.year||c.learningYear||'')+' • '+(c.featured===false?'Not featured on home':'Featured on home'),i,'courses')).join('')||'<div class="empty">No additional courses yet.</div>'}</div><button class="btn btn-primary" data-new="courses"><i class="fa-solid fa-plus"></i> Add Course</button><div id="editor-courses" class="editor-slot"></div>`;}
  function renderVisibility(){const root=$('tab-visibility');if(!root)return;const v=state.data.visibility||{};const rows=[['projects','Academic Projects','Control whether the Projects section appears on the homepage.'],['experience','Professional Experience','Control the Professional Experience section.'],['education','Academic Background','Control the Academic Background section.'],['research','Academic Research Work','Control the Academic Research section.'],['certificates','Learning & Certifications','Control the Learning & Certifications section.'],['courses','Additional Courses','Control the new Additional Courses section.']];root.innerHTML=`<div class="editor"><h3>Homepage Section Visibility</h3><p class="editor-help">Use these switches to control which major sections are shown on the main page. Changes are saved locally first and become live after Publish Changes.</p><div class="visibility-list">${rows.map(([key,title,desc])=>`<label class="visibility-row"><span><strong>${title}</strong><small>${desc}</small></span><input type="checkbox" data-visibility="${key}" ${v[key]!==false?'checked':''}><b>${v[key]!==false?'Visible':'Hidden'}</b></label>`).join('')}</div><div class="editor-actions"><button class="btn btn-primary" data-save-visibility>Save Homepage Visibility</button></div></div>`;root.querySelectorAll('[data-visibility]').forEach(input=>input.addEventListener('change',()=>input.parentElement.querySelector('b').textContent=input.checked?'Visible':'Hidden'));}
  function renderEducation(){const root=$('tab-education');if(!root)return;const items=state.data.education||[];root.innerHTML=`<div class="item-list">${items.map((e,i)=>listCard(e.title,(e.institution||'')+' • '+(e.date||'')+' • '+(e.featured===false?'Not featured on home':'Featured on home'),i,'education')).join('')||'<div class="empty">No education entries yet.</div>'}</div><button class="btn btn-primary" data-new="education"><i class="fa-solid fa-plus"></i> Add Education</button><div id="editor-education" class="editor-slot"></div>`;}
  function renderResearch(){const root=$('tab-research');root.innerHTML=`<div class="item-list">${(state.data.research||[]).map((r,i)=>listCard(r.title,(r.type||'Academic Research')+' • '+((r.tags||[]).join(', '))+' • '+(r.featured===false?'Not featured on home':'Featured on home'),i,'research')).join('')||'<div class="empty">No research yet.</div>'}</div><button class="btn btn-primary" data-new="research"><i class="fa-solid fa-plus"></i> Add Research</button><div id="editor-research" class="editor-slot"></div>`;}
  function projectEditor(item={},idx=-1){const p=Object.assign({id:'',title:'',description:'',cover:'',label:'PROJECT',tech:[],repo:'https://github.com/saikat-71',report:'',overview:'',problem:'',solution:'',highlights:[],role:'',category:'',screenshots:[]},item);return `<div class="editor"><h3>${idx<0?'Add':'Edit'} project</h3><div class="editor-form"><div class="form-grid two"><label>Project title<input data-f="title" value="${esc(p.title)}"></label><label>Short label<input data-f="label" value="${esc(p.label)}" placeholder="ML / DATA"></label></div><label>Short description<textarea data-f="description">${esc(p.description)}</textarea></label><label>Project overview<textarea data-f="overview" rows="4">${esc(p.overview)}</textarea></label><div class="form-grid two"><label>Problem / context<textarea data-f="problem" rows="4">${esc(p.problem)}</textarea></label><label>Solution / approach<textarea data-f="solution" rows="4">${esc(p.solution)}</textarea></label></div><div class="form-grid three"><label>Technologies<input data-f="tech" value="${esc(p.tech.join(', '))}" placeholder="Python, R, Machine Learning"></label><label>Role / project type<input data-f="role" value="${esc(p.role)}" placeholder="Academic project"></label><label>Category<input data-f="category" value="${esc(p.category)}" placeholder="Data Analytics"></label></div><label>Key highlights — one point per line<textarea data-f="highlights">${esc((p.highlights||[]).join('\n'))}</textarea></label><div class="form-grid two"><label>GitHub / project link<input data-f="repo" value="${esc(p.repo)}"></label><label>Report PDF path<input data-f="report" value="${esc(p.report)}" placeholder="documents/project-report.pdf"></label></div><div class="form-grid two"><label>Cover image path<input data-f="cover" value="${esc(p.cover)}" placeholder="images/project-name.jpg"></label><label>Upload new cover<input type="file" accept="image/*" data-file="cover"></label></div><label>Upload project screenshots <input type="file" accept="image/*" data-file="screenshots" multiple></label><label class="check-label"><input type="checkbox" data-f="featured" ${p.featured!==false?'checked':''}> Feature this project on homepage</label><div class="editor-actions"><button class="mini-btn" data-cancel="projects">Cancel</button><button class="btn btn-primary" data-save="projects" data-index="${idx}">Save project</button></div></div></div>`}
  function skillEditor(item={},idx=-1){const s=Object.assign({id:'',title:'',icon:'fa-solid fa-star',skills:[],proficiency:{},note:''},item);const prof=Object.entries(s.proficiency||{}).map(([k,v])=>`${k}: ${v}`).join(', ');return `<div class="editor"><h3>${idx<0?'Add':'Edit'} skill group</h3><div class="editor-form"><div class="form-grid two"><label>Group title<input data-f="title" value="${esc(s.title)}"></label><label>Font Awesome icon<input data-f="icon" value="${esc(s.icon)}"></label></div><label>Skills <input data-f="skills" value="${esc(s.skills.join(', '))}" placeholder="Python, R, SQL"></label>${s.id==='programming'?`<label>Language proficiency (only programming languages)<input data-f="proficiency" value="${esc(prof)}" placeholder="C++: 78, Java: 72, C#: 88, Python: 82"></label>`:''}<label>Optional note<input data-f="note" value="${esc(s.note)}"></label><div class="editor-actions"><button class="mini-btn" data-cancel="skills">Cancel</button><button class="btn btn-primary" data-save="skills" data-index="${idx}">Save skill group</button></div></div></div>`}
  function certEditor(item={},idx=-1){const c=Object.assign({id:'',title:'',provider:'',reference:'',icon:'fa-solid fa-certificate',file:'',date:'',category:'',credentialUrl:''},item);return `<div class="editor"><h3>${idx<0?'Add':'Edit'} certificate</h3><div class="editor-form"><div class="form-grid two"><label>Certificate title<input data-f="title" value="${esc(c.title)}"></label><label>Provider / course<input data-f="provider" value="${esc(c.provider)}"></label></div><div class="form-grid three"><label>Date / year<input data-f="date" value="${esc(c.date)}" placeholder="2026-05"></label><label>Category<input data-f="category" value="${esc(c.category)}" placeholder="Digital Marketing"></label><label>Reference / Credential ID<input data-f="reference" value="${esc(c.reference)}"></label></div><div class="form-grid two"><label>Credential URL<input data-f="credentialUrl" value="${esc(c.credentialUrl)}" placeholder="https://..."></label><label>Font Awesome icon<input data-f="icon" value="${esc(c.icon)}"></label></div><label>Certificate file path<input data-f="file" value="${esc(c.file)}" placeholder="documents/certificate.pdf"></label><label class="check-label"><input type="checkbox" data-f="featured" ${c.featured!==false?'checked':''}> Feature this certification on homepage</label><label>Upload certificate image/PDF<input type="file" accept="image/*,.pdf" data-file="file"></label><div class="editor-actions"><button class="mini-btn" data-cancel="certificates">Cancel</button><button class="btn btn-primary" data-save="certificates" data-index="${idx}">Save certificate</button></div></div></div>`}
  function expEditor(item={},idx=-1){
    const e=Object.assign({id:'',date:'',title:'',company:'',logo:'',showLogo:true,showPreviousWorks:true,description:[],joiningDate:'',endDate:'',currentlyWorking:false,featured:true,tools:[],skills:[],previousWorks:[]},item);
    const works=(e.previousWorks||[]).map(w=>`${w.title||''} | ${w.image||''}`).join('\n');
    return `<div class="editor"><h3>${idx<0?'Add':'Edit'} experience</h3><div class="editor-form">
      <div class="form-grid two"><label>Role / title<input data-f="title" value="${esc(e.title)}"></label><label>Company<input data-f="company" value="${esc(e.company)}"></label></div>
      <div class="form-grid three"><label>Joining date<input data-f="joiningDate" value="${esc(e.joiningDate||'')}" placeholder="May 2025"></label><label>End date<input data-f="endDate" value="${esc(e.endDate||'')}" placeholder="July 2026"></label><label class="check-label"><input type="checkbox" data-f="currentlyWorking" ${e.currentlyWorking?'checked':''}> Currently working here</label></div><label class="check-label"><input type="checkbox" data-f="featured" ${e.featured!==false?'checked':''}> Feature on homepage</label>
      <div class="form-grid two"><label>Legacy date / period<input data-f="date" value="${esc(e.date||'')}" placeholder="Used only if joining/end dates are empty"></label><label>Company logo path<input data-f="logo" value="${esc(e.logo)}" placeholder="images/company-logo.png"></label></div><div class="form-grid two"><label class="check-label"><input type="checkbox" data-f="showLogo" ${e.showLogo!==false?'checked':''}> Show company logo</label><label class="check-label"><input type="checkbox" data-f="showPreviousWorks" ${e.showPreviousWorks!==false?'checked':''}> Enable Previous Works button</label></div>
      <label>Description — one point per line<textarea data-f="description" rows="5">${esc((e.description||[]).join('\n'))}</textarea></label>
      <div class="form-grid two"><label>Tools — comma separated<input data-f="tools" value="${esc((e.tools||[]).join(', '))}" placeholder="Canva, Photoshop, CapCut"></label><label>Skills — comma separated<input data-f="skills" value="${esc((e.skills||[]).join(', '))}" placeholder="Graphic Design, Content Design, Digital Marketing"></label></div>
      <div class="experience-work-editor"><div class="editor-subhead"><div><strong>Previous works</strong><span>Add one work per line: Work title | image path</span></div><span class="editor-badge">Optional</span></div>
      <textarea data-f="previousWorks" rows="7" placeholder="Campaign Creative 01 | images/company/work-01.webp">${esc(works)}</textarea>
      <p class="editor-help">Previous works stay hidden until the visitor selects <strong>View Previous Works</strong> on the dedicated Experience page.</p>
      <label>Upload previous work images <input type="file" accept="image/*" data-file="previousWorks" multiple></label></div>
      <label>Upload company logo<input type="file" accept="image/*" data-file="logo"></label>
      <div class="editor-actions"><button class="mini-btn" data-cancel="experience">Cancel</button><button class="btn btn-primary" data-save="experience" data-index="${idx}">Save Experience</button></div>
    </div></div>`;
  }
  function educationEditor(item={},idx=-1){const e=Object.assign({id:'',date:'',title:'',institution:'',major:'',category:'',icon:'fa-solid fa-graduation-cap',description:'',featured:true},item);return `<div class="editor"><h3>${idx<0?'Add':'Edit'} education</h3><div class="editor-form"><div class="form-grid two"><label>Degree / qualification<input data-f="title" value="${esc(e.title)}"></label><label>Date / period<input data-f="date" value="${esc(e.date)}"></label></div><div class="form-grid two"><label>Major / group<input data-f="major" value="${esc(e.major)}" placeholder="Computer Science & Engineering / Science"></label><label>Education level<input data-f="category" value="${esc(e.category)}" placeholder="Undergraduate / HSC / SSC"></label></div><label>Institution<input data-f="institution" value="${esc(e.institution)}"></label><label>Font Awesome icon<input data-f="icon" value="${esc(e.icon)}"></label><label>Description<textarea data-f="description">${esc(e.description)}</textarea></label><label class="check-label"><input type="checkbox" data-f="featured" ${e.featured!==false?'checked':''}> Feature this academic background item on homepage</label><div class="editor-actions"><button class="mini-btn" data-cancel="education">Cancel</button><button class="btn btn-primary" data-save="education" data-index="${idx}">Save education</button></div></div></div>`;}
  function courseEditor(item={},idx=-1){const c=Object.assign({id:'',title:'',provider:'',year:'',learningYear:'',description:'',tools:[],skills:[],icon:'fa-solid fa-graduation-cap',featured:true,certificateDate:'',certificateReference:'',certificateFile:''},item);return `<div class="editor"><h3>${idx<0?'Add':'Edit'} additional course</h3><div class="editor-form"><div class="form-grid two"><label>Course title<input data-f="title" value="${esc(c.title)}"></label><label>Where did you learn it?<input data-f="provider" value="${esc(c.provider)}" placeholder="Coursera, Udemy, YouTube, Future IT..."></label></div><div class="form-grid three"><label>Learning year<input data-f="year" value="${esc(c.year||c.learningYear||'')}" placeholder="2026"></label><label>Certificate / issue date<input data-f="certificateDate" value="${esc(c.certificateDate||'')}" placeholder="06-09-2024"></label><label>Certificate reference<input data-f="certificateReference" value="${esc(c.certificateReference||'')}" placeholder="Reference number"></label></div><label>Details / description<textarea data-f="description" rows="5">${esc(c.description||'')}</textarea><div class="form-grid two"><label>Tools — comma separated<input data-f="tools" value="${esc((c.tools||[]).join(', '))}" placeholder="Python, Excel, Power BI"></label><label>Skills — comma separated<input data-f="skills" value="${esc((c.skills||[]).join(', '))}" placeholder="Data Analysis, Visualization"></label></div><label>Certificate file path<input data-f="certificateFile" value="${esc(c.certificateFile||'')}" placeholder="documents/certificate.pdf"></label><label>Font Awesome icon<input data-f="icon" value="${esc(c.icon)}"></label><label class="check-label"><input type="checkbox" data-f="featured" ${c.featured!==false?'checked':''}> Feature this course on homepage</label><div class="editor-actions"><button class="mini-btn" data-cancel="courses">Cancel</button><button class="btn btn-primary" data-save="courses" data-index="${idx}">Save Course</button></div></div></div>`;}
    function researchEditor(item={},idx=-1){const r=Object.assign({id:'',title:'',type:'Academic Research',method:'',dataset:'',models:'',status:'',abstract:'',description:'',problem:'',gap:'',methodology:'',results:'',tags:[],meta:'',report:'',presentation:'',featured:true},item);return `<div class="editor"><h3>${idx<0?'Add':'Edit'} research</h3><div class="editor-form"><label>Research title<input data-f="title" value="${esc(r.title)}"></label><div class="form-grid two"><label>Research type<input data-f="type" value="${esc(r.type)}" placeholder="Conference Research"></label><label>Research method<input data-f="method" value="${esc(r.method)}" placeholder="Survey / Machine Learning / Mixed Method"></label></div><div class="form-grid two"><label>Dataset<input data-f="dataset" value="${esc(r.dataset)}" placeholder="5,000 transaction records"></label><label>Models<input data-f="models" value="${esc(r.models)}" placeholder="Random Forest, XGBoost"></label></div><label>Status<input data-f="status" value="${esc(r.status)}" placeholder="Completed / Ongoing / Proposal"></label><label>Abstract<textarea data-f="abstract" rows="5">${esc(r.abstract||r.description)}</textarea></label><div class="form-grid two"><label>Research Problem<textarea data-f="problem" rows="5">${esc(r.problem)}</textarea></label><label>Research Gap<textarea data-f="gap" rows="5">${esc(r.gap)}</textarea></label></div><label>Methodology<textarea data-f="methodology" rows="6">${esc(r.methodology)}</textarea></label><label>Results<textarea data-f="results" rows="5">${esc(r.results)}</textarea></label><label>Tags <input data-f="tags" value="${esc(r.tags.join(', '))}" placeholder="Machine Learning, Data Science, E-Commerce"></label><label class="check-label"><input type="checkbox" data-f="featured" ${r.featured!==false?'checked':''}> Feature this research work on homepage</label><div class="form-grid two"><label>Research Report path<input data-f="report" value="${esc(r.report)}" placeholder="documents/research-report.pdf"></label><label>Presentation path<input data-f="presentation" value="${esc(r.presentation)}" placeholder="documents/research-presentation.pptx"></label></div><div class="form-grid two"><label>Upload research report<input type="file" accept="application/pdf" data-file="report"></label><label>Upload presentation<input type="file" accept=".ppt,.pptx,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation" data-file="presentation"></label></div><p class="editor-help">These fields appear on the dedicated Research Dashboard. Tags are separated by commas. Uploaded files are stored under <code>documents/</code> automatically when no path is provided.</p><div class="editor-actions"><button class="mini-btn" data-cancel="research">Cancel</button><button class="btn btn-primary" data-save="research" data-index="${idx}">Save research</button></div></div></div>`;}
  function openEditor(kind,idx){const item=idx>=0?state.data[kind][idx]:{};const html=kind==='projects'?projectEditor(item,idx):kind==='skills'?skillEditor(item,idx):kind==='certificates'?certEditor(item,idx):kind==='experience'?expEditor(item,idx):kind==='courses'?courseEditor(item,idx):kind==='education'?educationEditor(item,idx):researchEditor(item,idx);$('editor-'+kind).innerHTML=html;$('editor-'+kind).scrollIntoView({behavior:'smooth',block:'nearest'});}
  function readFields(box){const o={};box.querySelectorAll('[data-f]').forEach(el=>o[el.dataset.f]=el.value);return o}
  function saveAbout(){const root=$('tab-about');const a=state.data.about||{};const get=k=>root.querySelector(`[data-about="${k}"]`)?.value||'';const lines=v=>v.split(/\n+/).map(x=>x.trim()).filter(Boolean);a.heroName=get('heroName').trim();a.heroSubtitle=get('heroSubtitle').trim();a.heading=get('heading').trim();a.paragraphs=lines(get('paragraphs'));a.facts=lines(get('facts')).map(x=>{const [label,value,...rest]=x.split('|');return {label:(label||'').trim(),value:(value||'').trim(),icon:rest.join('|').trim()||'fa-solid fa-circle-info'}}).filter(x=>x.label||x.value);state.data.about=a;state.data.site=state.data.site||{};state.data.site._dirty=true;markDirty();renderAll();toast('About content saved locally. Click Publish Changes to make it live.');}
  function saveVisibility(){const root=$('tab-visibility');const v={};root.querySelectorAll('[data-visibility]').forEach(i=>v[i.dataset.visibility]=i.checked);state.data.visibility=v;state.data.site=state.data.site||{};state.data.site._dirty=true;markDirty();renderAll();toast('Homepage visibility saved locally. Click Publish Changes to make it live.');}
  async function saveItem(kind,idx,btn){const editor=btn.closest('.editor');const f=readFields(editor);
    let item={...f};
    if(kind==='projects'){item.tech=(f.tech||'').split(',').map(x=>x.trim()).filter(Boolean);item.highlights=(f.highlights||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);item.featured=editor.querySelector('[data-f=featured]')?.checked!==false}
    if(kind==='courses'){item.tools=(f.tools||'').split(',').map(x=>x.trim()).filter(Boolean);item.skills=(f.skills||'').split(',').map(x=>x.trim()).filter(Boolean);item.featured=editor.querySelector('[data-f=featured]')?.checked!==false;}
    if(kind==='experience'){
      item.description=(f.description||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
      item.joiningDate=(f.joiningDate||'').trim();
      item.endDate=(f.endDate||'').trim();
      item.currentlyWorking=editor.querySelector('[data-f=currentlyWorking]')?.checked||false;
      item.featured=editor.querySelector('[data-f=featured]')?.checked!==false;
      item.showLogo=editor.querySelector('[data-f=showLogo]')?.checked!==false;
      item.showPreviousWorks=editor.querySelector('[data-f=showPreviousWorks]')?.checked!==false;
      item.tools=(f.tools||'').split(',').map(x=>x.trim()).filter(Boolean);
      item.skills=(f.skills||'').split(',').map(x=>x.trim()).filter(Boolean);
      item.previousWorks=(f.previousWorks||'').split(/\n+/).map(x=>{
        const parts=x.split('|'); return {title:(parts.shift()||'').trim(),image:parts.join('|').trim()};
      }).filter(x=>x.title||x.image);
    }
    if(kind==='certificates'){item.featured=editor.querySelector('[data-f=featured]')?.checked!==false;}
    if(kind==='education'){item.featured=editor.querySelector('[data-f=featured]')?.checked!==false;}
    if(kind==='research'){item.featured=editor.querySelector('[data-f=featured]')?.checked!==false;}
    if(kind==='skills'){item.skills=(f.skills||'').split(',').map(x=>x.trim()).filter(Boolean);if(f.proficiency!==undefined){item.proficiency={};(f.proficiency||'').split(',').forEach(pair=>{const [name,val]=pair.split(':');if(name&&val)item.proficiency[name.trim()]=Math.max(0,Math.min(100,Number(val.trim())||0))})}}
    if(kind==='research')item.tags=(f.tags||'').split(',').map(x=>x.trim()).filter(Boolean);
    if(idx<0)item.id=slug(item.title)+'-'+Date.now().toString(36);else item.id=state.data[kind][idx].id||slug(item.title);
    for(const el of editor.querySelectorAll('input[type=file][data-file]')){const files=Array.from(el.files||[]);if(!files.length)continue;if(el.dataset.file==='screenshots'&&kind==='projects'){item.screenshots=Array.isArray(item.screenshots)?item.screenshots.slice():[];for(const file of files){const path='images/projects/'+slug(item.title)+'-'+slug(file.name.replace(/\.[^.]+$/,''))+'-'+Date.now().toString(36)+'.'+file.name.split('.').pop().toLowerCase();item.screenshots.push(path);state.pendingFiles.push({path,file})}}else{
      if(el.dataset.file==='previousWorks'&&kind==='experience'){
        item.previousWorks=Array.isArray(item.previousWorks)?item.previousWorks.slice():[];
        for(const file of files){
          const ext=file.name.split('.').pop().toLowerCase();
          const base=slug(file.name.replace(/\.[^.]+$/,''));
          const path='images/experience/'+slug(item.company||item.title||'company')+'-'+base+'-'+Date.now().toString(36)+'.'+ext;
          item.previousWorks.push({title:file.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ').trim()||'Previous Work',image:path});
          state.pendingFiles.push({path,file});
        }
      }else{
        const file=files[0];let path=item[el.dataset.file];
        if(!path){const folder=kind==='projects'?(el.dataset.file==='cover'?'images/projects':'documents'):(kind==='certificates'||kind==='research'?'documents':'images');path=folder+'/'+slug(item.title)+'-'+slug(file.name.replace(/\.[^.]+$/,''))+'.'+file.name.split('.').pop().toLowerCase();item[el.dataset.file]=path}
        state.pendingFiles.push({path,file})
      }
    }}
    if(idx<0)state.data[kind].push(item);else state.data[kind][idx]=item;state.data.site=state.data.site||{};state.data.site._dirty=true;markDirty();renderAll();toast('Saved locally. Click Publish Changes to make it live.');}
  async function publish(){if(!state.data)return;const btn=$('publishBtn');btn.disabled=true;btn.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Publishing...';try{for(const pf of state.pendingFiles){await uploadFile(pf.path,pf.file)}state.data.site=state.data.site||{};state.data.site.lastUpdated=new Date().toISOString().slice(0,10);delete state.data.site._dirty;const current=await getFile(DATA_PATH);const body={message:'admin: update portfolio content',content:b64utf8(JSON.stringify(state.data,null,2)+'\n'),branch:state.branch};if(current?.sha)body.sha=current.sha;const r=await api(`/repos/${state.owner}/${state.repo}/contents/${DATA_PATH}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).message||'Publish failed');state.pendingFiles=[];await loadData();const dirty=$('adminDirty');if(dirty)dirty.classList.remove('show');toast('Published successfully. Your GitHub Pages site will update automatically.');}catch(e){toast(e.message||'Publish failed.',true)}finally{btn.disabled=false;btn.innerHTML='<i class="fa-solid fa-cloud-arrow-up"></i> Publish Changes'}}
  function exportJson(){const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio.json';a.click();URL.revokeObjectURL(a.href)}
  document.addEventListener('click',e=>{const tab=e.target.closest('.admin-tabs button');if(tab){document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$('tab-'+tab.dataset.tab).classList.add('active');return}const edit=e.target.closest('[data-edit]');if(edit){openEditor(edit.dataset.edit,+edit.dataset.index);return}const nw=e.target.closest('[data-new]');if(nw){openEditor(nw.dataset.new,-1);return}const cancel=e.target.closest('[data-cancel]');if(cancel){$('editor-'+cancel.dataset.cancel).innerHTML='';return}const del=e.target.closest('[data-delete]');if(del){const kind=del.dataset.delete,idx=+del.dataset.index;if(confirm('Delete this item? This will be removed when you publish.')){state.data[kind].splice(idx,1);state.data.site=state.data.site||{};state.data.site._dirty=true;markDirty();renderAll();toast('Deleted locally. Publish to apply.')}return}const saveAboutBtn=e.target.closest('[data-save-about]');if(saveAboutBtn){saveAbout();return}const saveVisibilityBtn=e.target.closest('[data-save-visibility]');if(saveVisibilityBtn){saveVisibility();return}const save=e.target.closest('[data-save]');if(save){saveItem(save.dataset.save,+save.dataset.index,save);return}});
  const cursorDot=document.querySelector('.cursor-dot'),cursorRing=document.querySelector('.cursor-ring');if(cursorDot&&cursorRing&&matchMedia('(pointer:fine)').matches){const move=e=>{cursorDot.style.transform=`translate(${e.clientX}px,${e.clientY}px) translate(-50%,-50%)`;cursorRing.style.transform=`translate(${e.clientX}px,${e.clientY}px) translate(-50%,-50%)`};addEventListener('mousemove',move,{passive:true});document.addEventListener('pointerover',e=>{if(e.target.closest('a,button,input,textarea,.item-card'))cursorRing.classList.add('active')});document.addEventListener('pointerout',e=>{if(e.target.closest('a,button,input,textarea,.item-card')&&!e.relatedTarget?.closest('a,button,input,textarea,.item-card'))cursorRing.classList.remove('active')})}
  $('connectBtn').addEventListener('click',connect);$('publishBtn').addEventListener('click',publish);$('exportBtn').addEventListener('click',exportJson);
  const theme=$('themeToggle');const body=document.body;const applyAdminTheme=()=>{const light=localStorage.getItem('saikat-theme')==='light';body.classList.toggle('light',light);document.documentElement.dataset.theme=light?'light':'dark';if(theme){theme.setAttribute('aria-pressed',String(light));theme.setAttribute('title',light?'Switch to dark mode':'Switch to light mode');theme.setAttribute('aria-label',light?'Switch to dark mode':'Switch to light mode');const icon=theme.querySelector('i');if(icon)icon.className=light?'fa-solid fa-moon':'fa-solid fa-sun'}};applyAdminTheme();theme.addEventListener('click',()=>{localStorage.setItem('saikat-theme',body.classList.contains('light')?'dark':'light');applyAdminTheme()});
})();
